export const COLORS = {
  WHITE: {
    900: '#FFFFFF',
    500: '#CCD',
  },
  BLACK: {
    900: '#444',
    500: '#222',
    100: '#111',
  },
  BLUE: {
    300: '#21213E',
    100: '#0E0E1D',
  },
}

export const STATES = {
  ak: 'Alaska',
  al: 'Alabama',
  ar: 'Arkansas',
  az: 'Arizona',
  ca: 'California',
  co: 'Colorado',
  ct: 'Connecticut',
  dc: 'District Of Columbia',
  de: 'Delaware',
  fl: 'Florida',
  ga: 'Georgia',
  hi: 'Hawaii',
  ia: 'Iowa',
  id: 'Idaho',
  il: 'Illinois',
  in: 'Indiana',
  ks: 'Kansas',
  ky: 'Kentucky',
  la: 'Louisiana',
  ma: 'Massachusetts',
  md: 'Maryland',
  me: 'Maine',
  mi: 'Michigan',
  mn: 'Minnesota',
  mo: 'Missouri',
  ms: 'Mississippi',
  mt: 'Montana',
  nc: 'North Carolina',
  nd: 'North Dakota',
  ne: 'Nebraska',
  nh: 'New Hampshire',
  nj: 'New Jersey',
  nm: 'New Mexico',
  nv: 'Nevada',
  ny: 'New York',
  oh: 'Ohio',
  ok: 'Oklahoma',
  or: 'Oregon',
  pa: 'Pennsylvania',
  ri: 'Rhode Island',
  sc: 'South Carolina',
  sd: 'South Dakota',
  tn: 'Tennessee',
  tx: 'Texas',
  ut: 'Utah',
  va: 'Virginia',
  vt: 'Vermont',
  wa: 'Washington',
  wi: 'Wisconsin',
  wv: 'West Virginia',
  wy: 'Wyoming',
};